global:
  scrape_interval: 5s

rule_files:
  - "alert_rules.yml"

scrape_configs:
  - job_name: "api-gateway"
    static_configs:
      - targets: ["api-gateway:8080"]

  - job_name: "auth-service"
    static_configs:
      - targets: ["auth-service:8080"]

  - job_name: "user-service"
    static_configs:
      - targets: ["user-service:8080"]

  - job_name: "product-service"
    static_configs:
      - targets: ["product-service:8080"]

  - job_name: "order-service"
    static_configs:
      - targets: ["order-service:8080"]

  - job_name: "payment-service"
    static_configs:
      - targets: ["payment-service:8080"]
